### ISSUE TITLE
What does server.hot option in vite.config file?

### ISSUE THREAD

**Issue by fedehiga** [twbs/examples#144]
in vite/vite.config.js file:
```
export default {
  server: {
    port: 8080,
    hot: true
  }
}
```

What does the 'hot: true' option does? I can't find that option in [vite official docs](https://vitejs.dev/config/server-options.html#server-options).

**Comment by julien-deramond** [comment]
Thanks for opening this issue @fedehiga.

I can't find it either, It was to enable hot reload which is apparently the case by default in Vite. But maybe that's a bad copy and paste from Webpack configuration (see https://webpack.js.org/guides/hot-module-replacement/).

We'll check that in detail, and if this is a bad copy and paste, we'll fix this repo, the Vue one, and also the Vite guide in Bootstrap docs.
