### ISSUE TITLE
Multi-page Vite example

### ISSUE THREAD

**Issue by rasselmrh** [twbs/examples#15]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

There is no instruction for production build with Vite JS & also how we can configure multipage bootstrap website using vite. please include a details documentation in the existing vite doc part.

### Motivation and context

Using Vite with Bootstrap for product ready website is confusing because there isn't any instruction about that.

**Comment by mdo** [comment]
I've transferred this issue to this examples repo as I don't think we have much intention about fleshing out the existing Vite guide to be more complicated.

**Comment by rasselmrh** [comment]
Any guidance on this topic would be nice and helpful

**Comment by mdo** [comment]
Reflecting on this more, I don't think we'll be adding it. None of our other examples have multiple pages and that's something you should tackle :). These are just to show how to setup Bootstrap in specific app frameworks. Good luck!
