### ISSUE TITLE
The Dropdown navbar is not working properly on the getbootstrap website

### ISSUE THREAD

**Issue by sahinmallick** [twbs/examples#382]
<img width="1440" alt="Screenshot 2024-01-31 at 9 46 48 PM" src="https://github.com/twbs/examples/assets/106900187/714d886f-9b7f-464e-91ad-18ee243520f7">
<img width="1440" alt="Screenshot 2024-01-31 at 9 49 59 PM" src="https://github.com/twbs/examples/assets/106900187/874d6c79-ff33-4f00-afbd-e5dcf3a53846">

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @sahinmallick but as there's no explanation nor reproducible example, I'm going to close this issue. Moreover, Bootstrap version 4 is EOL (support has ended and no more version 4 will be released). Please refer to a more recent v5 version in https://getbootstrap.com/.
