### ISSUE TITLE
Functions should be imported first , as the official docs recommends. Vite example

### ISSUE THREAD

**Issue by lucasdavidferrero** [twbs/examples#40]
Reading the Vite example, I note that functions are imported after variable overrides:
https://github.com/twbs/examples/blob/2a7f56d65be3b2cf971a9a61f2eaf57479aaef42/vite/src/scss/styles.scss#L40

Official docs recommend include the functions first:
https://getbootstrap.com/docs/5.3/customize/sass/#importing

**Comment by lucasdavidferrero** [comment]
Also note that there are 2 mistakes in the above example file:
1- Miss `@import "~bootstrap/scss/variables-dark";`
2- Wrong import path of helpers: `@import "helpers";` (should be `@import "~bootstrap/scss/helpers";`)

**Comment by julien-deramond** [comment]
Thanks for opening this issue @lucasdavidferrero. It's going to be fixed in https://github.com/twbs/examples/pull/41.
Regarding the missing import of `scss/variables-dark`, it is mainly because the v5.2.3 is still an alpha version. I'll discuss this topic in the PR with other maintainers.

**Comment by julien-deramond** [comment]
FYI the issue will be closed automatically when the PR will be merged.
