### ISSUE TITLE
Enable Dependabot for each sub-projects

### ISSUE THREAD

**Issue by julien-deramond** [twbs/examples#44]
Our examples are technically sub-projects that have their own dependencies in their `package.json`.

We should enable Dependabot for each sub-dir:
- color-modes
- icons-font
- parcel
- sass-js-esm
- sass-js
- starter
- vite
- vue
- webpack

ATM I only update "vite" deps because I think of it thanks to the notification I receive of their new releases.

**Comment by julien-deramond** [comment]
> any reason why we don't use workspaces in this repo? npm supports it natively nowadays and should help with maintenance.

Nope, I haven't checked anything around it. We can try.

> As for dependabot feel free to proceed, but keep in mind it can get too noisy.

I don't have the rights, that's why I've created this issue initially. And because I'm updating "vite" deps because I follow this project but the other deps aren't really updated so far.

**Comment by XhmikosR** [comment]
You should have the rights sincerity have push rights already. Seems like a
misconfiguration issue, we'll sort it out tomorrow!
