### ISSUE TITLE
Add a Vue3/Vite example

### ISSUE THREAD

**Issue by sunergeo** [twbs/examples#6]
I have submitted a pull request at https://github.com/twbs/examples/pull/5 to illustrate the issue I have encountered.

I am having trouble getting bootstrap to import into a basic Vue3/Vite app.  I have studied the other examples in this repository, and cannot figure out what I am missing.

When the project builds, the following error is generated:

ENOENT: no such file or directory, stat '[base path]/vite-vue/node_modules/bootstrap/scss/bootstrap'

This is coming from the vite:css plugin, and I can find no information about how to configure that plugin correctly.

I have verified my vite.config.js has the correct ~bootstrap alias by hard-coding the path to node_modules/bootstrap/scss/bootstrap, and the same error occurs.  If I reference the _bootstrap.scss file directly, another error occurs because the inline comments are unrecognized.

Any assistance would be greatly appreciated!

**Comment by mdo** [comment]
Your example isn't in line with the others we have in this a repo, so I've closed the PR for now.

We could add a Vue example here, but I'm not sure when we'll get around to it. When we do, there's no guarantee it'll be the setup that you need :). For now, consider asking around more as you've done in the main repo's discussions.

**Comment by sunergeo** [comment]
Ok, no problem ... I thought this would be helpful.

**Comment by mdo** [comment]
See #13.
